%%
%% This is file `democls.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% democls.dtx  (with options: `class')
%% ----------------------------------------------------------------
%% democls --- brief description
%% email: you+obfuscation@your.domain
%% GitHub: https://github.com/YourGitHubProfile
%% Released under the LaTeX Project Public License v1.3c or later
%% See http://www.latex-project.org/lppl.txt
%% ----------------------------------------------------------------
%% 
\def\fileversion{v1.0}
\def\filedate{2015/07/10}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{democls}[\filedate\space\fileversion\space description text]
\LoadClass{article}
\newcommand{\examplemacro}[2][]{%
  \textit{#1} --- \textbf{#2}
}
%% 
%% Copyright (C) 2009 by You <you+obfuscation@your.domain>
%% 
%% This work may be distributed and/or modified under the conditions of the LaTeX
%% Project Public License (LPPL), either version 1.3c of this license or (at your
%% option) any later version. The latest version of this license is in the file:
%% 
%% http://www.latex-project.org/lppl.txt
%% 
%% This work is "maintained" (as per LPPL maintenance status) by
%% You.
%% 
%% This work consists of the file
%%   democls.dtx
%% and the derived files
%%   democls.ins,
%%   democls.cls,
%%   democls.pdf, and
%%   example.tex.
%% 
%%
%% End of file `democls.cls'.
